version: '3'
services:
  notebook:
    build: .
    image: sjawhar/lunar-lander
    container_name: lunar-lander
    environment:
      - "DISPLAY=10.0.75.1:0"
    volumes:
      - "./agent:/home/jovyan"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    ports:
      - "8888:8888"
    command:
      - "start-notebook.sh"
      - "--NotebookApp.token=''"
